namespace ShogiNet
{
    public enum ClientRequest
    {
        None,
        Login,
        SignUp,
        SignUpInfo,
        AccountInfo,
        UserInfo,
        CreateGame,
        CloseGame,
        HostData,
        JoinGame,
        StopJoining,
        GameStart,
        GameData,
        PlayerData,
        SendMove,
        SendDrop,
        GameResult,
        Takeback,
        TakebackYes,
        TakebackNo,
        SendMoveString,
        NotifyReady,
        ChangeAvatar,
        ChangeCountry,
        ChangePassword,
        DeleteYourself,
        DeleteAccount,
        AcceptJoiner,
        DeclineJoiner
    }
}
