extends Node

# Settings.gd
# Содержит все настройки записываемые в профиль

# Цвета
enum WebColor {
	GAINSBORO,
	LIGHT_GRAY,
	SILVER,
	DARK_GRAY,
	GRAY,
	DIM_GRAY,
	LIGHT_SLATE_GRAY,
	SLATE_GRAY,
	DARK_SLATE_GRAY,
	BLACK,
	WHITE
}


func get_color(web_color):
	match web_color:
		WebColor.GAINSBORO:
			return Color("DCDCDC")
		WebColor.LIGHT_GRAY:
			return Color("D3D3D3")
		WebColor.SILVER:
			return Color("C0C0C0")
		WebColor.DARK_GRAY:
			return Color("A9A9A9")
		WebColor.GRAY:
			return Color("808080")
		WebColor.DIM_GRAY:
			return Color("696969")
		WebColor.LIGHT_SLATE_GRAY:
			return Color("778899")
		WebColor.SLATE_GRAY:
			return Color("708090")
		WebColor.DARK_SLATE_GRAY:
			return Color("2F4F4F")
		WebColor.BLACK:
			return Color("000000")
		WebColor.WHITE:
			return Color("ffffff")

# Язык игры
enum Language {
	DEFAULT = 0,
	ENGLISH = 0,
	RUSSIAN = 1,
	CHINESE = 2,
	JAPANESE = 3
}

# Опции подсветки
enum HighlightOptions {
	DISABLED = 0,
	MYSELF = 1,
	ALL = 2
}

# Список всех настроек
enum {
	SV_UI_LANGUAGE,
	SV_UI_THEME,
	SV_UI_ASPECT,
	SV_UI_FONT,
	SV_UI_FONT_OUTLINE_ENABLED,
	SV_UI_TIPS_BUTTON_ENABLED,
	SV_UI_PANEL_TRANSPARENCY,
	SV_AI_ENGINE_FOLDER,
	SV_AI_ENGINE_EXE,
	SV_AI_ENGINE_SKILL_LEVEL,
	SV_AI_ENGINE_ENABLE_LOG,
	SV_GAME_AUTOMOVE_ENABLED,
	SV_GAME_AUTOPROMOTION_ENABLED,
	SV_GAME_LASTMOVE_ENABLED,
	SV_GAME_CASTLES_ENABLED,
	SV_GAME_AUTOSHOW,
	SV_GAME_ANIM_SPEED,
	SV_GAME_ANIM_LIFTUP_ENABLED,
	SV_GAME_ANIM_DROP_ENABLED,
	SV_GAME_ANIM_TAKE_ENABLED,
	SV_HISTORY_AUTOSHOW_ENABLED,
	SV_HISTORY_AUTOSCROLL_ENABLED,
	SV_HISTORY_ELEMENT_COUNT,
	SV_HISTORY_PANEL_STYLE,
	SV_HISTORY_PANEL_SIZE,
	SV_HISTORY_PLAYBACK_REVERT,
	SV_HISTORY_PLAYBACK_IS_FIXED,
	SV_HISTORY_PLAYBACK_FIXED_DURATION,
	SV_HISTORY_NOTATION_STYLE,
	SV_HISTORY_NOTATION_USE_Y_NUMBER,
	SV_HISTORY_DRAW_TURN_SYMBOL,
	SV_HISTORY_SYMBOLS,
	SV_CAMERA_YAW_ENABLED,
	SV_CAMERA_PITCH_ENABLED,
	SV_CAMERA_ZOOM_ENABLED,
	SV_CAMERA_PAN_ENABLED,
	SV_CAMERA_SWITCH_ENABLED,
	SV_CAMERA_RESTRICT_YAW,
	SV_STYLES_BOARD_MARKUP_ENABLED,
	SV_STYLES_BOARD_COLORING_UI_ENABLED,
	SV_STYLES_BOARD_COLORING_CHESS_ENABLED,
	SV_STYLES_BOARD_COLORING_ZONES_ENABLED,
	SV_STYLES_GRID_COLOR,
	SV_STYLES_GRID_THICKNESS,
	SV_STYLES_PIECE_THEME,
	SV_SFX_UI_ENABLED,
	SV_SFX_UI_VOLUME,
	SV_SFX_MOVE_ENABLED,
	SV_SFX_MOVE_VOLUME,
	SV_SFX_3D_ENABLED,
	SV_SFX_SPEECH_ENABLED,
	SV_SFX_SPEECH_VOLUME,
	SV_SFX_CHECK_ENABLED,
	SV_SFX_MUSIC_ENABLED,
	SV_SFX_MUSIC_VOLUME,
	SV_SFX_MUSIC_ORDER,
	SV_WIDGET_SANSARA_ENABLED,
	SV_WIDGET_SANSARA_ORDER,
	SV_WIDGET_CLOCK_ENABLED,
	SV_WIDGET_CLOCK_SECONDS_ENABLED,
	SV_WIDGET_CLOCK_ZEROES_ENABLED,
	SV_WIDGET_CLOCK_FORMAT,
	SV_WIDGET_QQ_ENABLED,
	SV_WIDGET_QQ_DIALOG_ENABLED,
	SV_IPV4_1,
	SV_IPV4_2,
	SV_IPV4_3,
	SV_IPV4_4,
	SV_JOIN_PORT,
	SV_IPV6,
	SV_MASTER_IPV4_1,
	SV_MASTER_IPV4_2,
	SV_MASTER_IPV4_3,
	SV_MASTER_IPV4_4,
	SV_MASTER_IPV6,
	SV_MASTER_PORT,
	SV_MASTER_USE_IPV6,
	SV_LOOPBACK_MODE,
	SV_MP_PASSWORD,
	SV_MP_SAVE_PASSWORD,
	SV_MP_SIGNED,
	# KEYS
	SV_KEY_CAMERA_ROTATE_LEFT_DEF,
	SV_KEY_CAMERA_ROTATE_LEFT,
	SV_KEY_CAMERA_ROTATE_LEFT2_DEF,
	SV_KEY_CAMERA_ROTATE_LEFT2,
	SV_KEY_CAMERA_ROTATE_RIGHT_DEF,
	SV_KEY_CAMERA_ROTATE_RIGHT,
	SV_KEY_CAMERA_ROTATE_RIGHT2_DEF,
	SV_KEY_CAMERA_ROTATE_RIGHT2,
	SV_KEY_CAMERA_ROTATE_UP_DEF,
	SV_KEY_CAMERA_ROTATE_UP,
	SV_KEY_CAMERA_ROTATE_UP2_DEF,
	SV_KEY_CAMERA_ROTATE_UP2,
	SV_KEY_CAMERA_ROTATE_DOWN_DEF,
	SV_KEY_CAMERA_ROTATE_DOWN,
	SV_KEY_CAMERA_ROTATE_DOWN2_DEF,
	SV_KEY_CAMERA_ROTATE_DOWN2,
	SV_KEY_CAMERA_RESET_DEF,
	SV_KEY_CAMERA_RESET,
	SV_KEY_CAMERA_RESET2_DEF,
	SV_KEY_CAMERA_RESET2,
	SV_KEY_FLIP_BOARD_DEF,
	SV_KEY_FLIP_BOARD,
	SV_KEY_FLIP_BOARD2_DEF,
	SV_KEY_FLIP_BOARD2,
	SV_KEY_SHOW_HISTORY_DEF,
	SV_KEY_SHOW_HISTORY,
	SV_KEY_SHOW_HISTORY2_DEF,
	SV_KEY_SHOW_HISTORY2,
	SV_KEY_HISTORY_BACK_DEF,
	SV_KEY_HISTORY_BACK,
	SV_KEY_HISTORY_BACK2_DEF,
	SV_KEY_HISTORY_BACK2,
	SV_KEY_HISTORY_FORWARD_DEF,
	SV_KEY_HISTORY_FORWARD,
	SV_KEY_HISTORY_FORWARD2_DEF,
	SV_KEY_HISTORY_FORWARD2,
	SV_KEY_HISTORY_PLAY_REVERSED_DEF,
	SV_KEY_HISTORY_PLAY_REVERSED,
	SV_KEY_HISTORY_PLAY2_REVERSED_DEF,
	SV_KEY_HISTORY_PLAY2_REVERSED,
	SV_KEY_HISTORY_PLAY_DEF,
	SV_KEY_HISTORY_PLAY,
	SV_KEY_HISTORY_PLAY2_DEF,
	SV_KEY_HISTORY_PLAY2,
	SV_KEY_HISTORY_TO_START_DEF,
	SV_KEY_HISTORY_TO_START,
	SV_KEY_HISTORY_TO_START2_DEF,
	SV_KEY_HISTORY_TO_START2,
	SV_KEY_HISTORY_TO_END_DEF,
	SV_KEY_HISTORY_TO_END,
	SV_KEY_HISTORY_TO_END2_DEF,
	SV_KEY_HISTORY_TO_END2,
	SV_KEY_TOGGLE_HINT_MODE_DEF,
	SV_KEY_TOGGLE_HINT_MODE,
	SV_KEY_TOGGLE_HINT_MODE2_DEF,
	SV_KEY_TOGGLE_HINT_MODE2,

	SV_LIMITER
}